"""Plain-language explanations shared by hover hints and dismissible popovers."""
WHY = {
    "rooms": "Makes the size of the monitored estate clear before you compare results.",
    "utilisation": "Helps workplace leaders see where demand is concentrated and where to investigate spare space.",
    "attendance": "Helps compare the size of groups using rooms with the sizes of rooms you provide.",
    "reviews": "Focuses attention on a manageable set of rooms with evidence behind the recommendation.",
    "heatmap": "Reveals peak periods that a single average can hide, supporting space and scheduling decisions.",
    "fit": "Helps identify a possible mismatch between room sizes and actual group sizes.",
    "focus": "Connects a sensor observation to an accountable next step for workplace or facilities teams.",
    "coverage": "Shows whether there is enough evidence to trust a comparison; a quiet room and missing data are different things.",
    "environment": "Helps facilities teams identify recurring conditions that may affect the room experience.",
    "trend": "Lets you check when a condition occurred before deciding how to respond.",
    "fleet": "Helps operations teams identify rooms that may need attention and understand the platform mix.",
    "ask": "Provides a quick route to common decisions without having to interpret every chart.",
    "workflow": "Shows how observed evidence could become a useful request for investigation in an external system.",
}
HELP = {
    "rooms": ("Rooms monitored", "Distinct named meeting spaces in the selected scope.",
        "Counted once per location and room name, with at least one record in the selected period. Assets with a recorded capacity of zero, and spaces with no capacity metadata, are excluded by default. You can include them under More filters.",
        "A monitored room is not necessarily online now. Aliases for the same physical room need to be reconciled in the source."),
    "utilisation": ("Space utilisation", "How often monitored rooms are occupied.",
        "Occupied room-hours divided by valid observed room-hours, multiplied by 100. Each reading is weighted by elapsed time to the next reading, capped at that room's sampling cadence. Office hours means weekdays, 08:00–19:00 in the recorded source clock.",
        "Missing, offline and unknown-status readings do not count as empty. A low average can coexist with high peak demand."),
    "attendance": ("Typical attendance", "Average people present while rooms are occupied.",
        "Observed person-hours divided by occupied room-hours. Empty periods are excluded. This is a time-weighted average, not the average number of invitees or meeting participants.",
        "Sensor people counts may miss people outside the supported view. They do not identify individuals."),
    "reviews": ("Rooms to review", "Rooms with enough observed evidence for investigation.",
        "Unique rooms with at least one finding: repeated warm or bright empty periods, or consistently low attendance relative to capacity. Thresholds are visible and adjustable under More filters. The overview shows one finding per room, ranked by evidence hours.",
        "These are investigation candidates, not confirmed faults, energy savings or business-case approvals."),
    "heatmap": ("When are rooms busiest?", "Compare occupancy patterns across days and times.",
        "Each cell is occupied time divided by valid observed time in that weekday/time band across selected rooms. Hover over a cell for its percentage and observed hours. Grey gaps mean no valid observations.",
        "Use the Spaces page to investigate individual rooms. Missing data and public holidays can affect comparisons."),
    "fit": ("Room fit", "Check whether attendance matches available seats.",
        "Uses time-weighted attendance during occupied periods and the recorded capacity for each room. P90 is the count at or below which 90% of observed occupied time falls. A review candidate needs at least two occupied hours, at least four seats and P90 attendance no greater than half the capacity.",
        "Peak demand, accessibility, room purpose and a representative history must be considered before reducing capacity."),
    "focus": ("Decisions to explore", "A short, evidence-based list of next steps.",
        "The overview prioritises a data check when any selected room has less than 70% occupancy coverage. Remaining candidates use rooms at or above that review threshold, ordered by qualifying evidence hours, with one finding per room. This is a completeness screen, not statistical confidence. Insights retains all findings, including rooms with limited coverage.",
        "Warmth does not prove heating is running. Brightness can come from daylight. Booking, BMS and meter integrations are required for stronger claims."),
    "coverage": ("Data coverage", "How much of the selected period has valid occupancy observations.",
        "Valid occupancy room-hours divided by scheduled room-hours across rooms in scope. Gaps are capped at sampling cadence and offline/unknown readings are excluded. Each room is treated as in scope for the full selected period because commissioning dates are not supplied.",
        "This measures observation coverage, not sensor accuracy or device uptime. Environmental sensor coverage is reported separately. The period stops at the latest timestamp in the feed."),
    "environment": ("Room conditions", "Review recurring environmental signals.",
        "Charts show available temperature, humidity, VOC concentration and light readings. Empty-room findings require valid zero occupancy and a valid environmental reading at the same time. Thresholds are investigation settings, not medical or compliance limits.",
        "VOC is shown as the source's VOC field; only label it ppb after confirming the collector writes concentration. Do not mix it with VOC Index. None of these readings establishes energy consumption."),
    "trend": ("Room history", "Explore the evidence behind a finding.",
        "Occupancy uses valid observation intervals. Other signals require a reporting device and a non-missing reading. Charts leave gaps in missing observations and use straight lines rather than a smoothed curve.",
        "Reading averages are displayed for environmental trend aggregation. Export the source observations for exact timestamps."),
    "fleet": ("Latest recorded status", "The latest observation per named room in your selected period.",
        "The timestamp beside each room tells you when the status was observed. Platform counts use one latest record per room, not repeated telemetry samples or claimed meeting sessions.",
        "These are historical snapshots when a past date range is selected. Online does not certify that every part of a meeting room works."),
    "ask": ("Explore a question", "Guided analysis of the selected observations.",
        "Choose a question to retrieve the same calculated findings used elsewhere in the app. Results always retain the selected locations, dates, hours and evidence thresholds.",
        "This is a deterministic analysis helper, not a connected language model. It does not send commands or create external tickets."),
    "workflow": ("Workflow preview", "Inspect a proposed handoff to a facilities system.",
        "A selected finding can be exported as a draft JSON request containing the evidence, owner and suggested investigation. This previews an integration contract for future ServiceNow and BMS work.",
        "No outbound webhook, ticket, device reboot or BMS control is executed. Implementation requires an authenticated integration and verified outcomes."),
}
