[theme]
base = "light"
primaryColor = "#5F259F"
backgroundColor = "#F6F7F8"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#333333"
font = "sans serif"

[client]
showSidebarNavigation = false

[browser]
gatherUsageStats = false
